apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: xllama3
spec:
  modelName: meta-llama/Meta-Llama-3-8B
  criticality: Standard
  poolRef:
    name: vllm-llama3-8b-instruct
