apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: inferencemodel-sample
spec:
  modelName: llama3
  criticality: Standard
  poolRef:
    name: vllm-llama3-8b-instruct
